USE ProyectoFinal;

INSERT INTO PAISES (NOMBRE, DOMINIO) VALUES
  ("Afganistán","AF"),
  ("Albania","AL"),
  ("Alemania","DE"),
  ("Andorra","AD"),
  ("Angola","AO"),
  ("Anguila","AI"),
  ("Antártida","AQ"),
  ("Antigua y Barbuda","AG"),
  ("Arabia Saudita","SA"),
  ("Argelia","DZ"),
  ("Argentina","AR"),
  ("Armenia","AM"),
  ("Aruba","AW"),
  ("Australia","AU"),
  ("Austria","AT"),
  ("Azerbaiyán","AZ"),
  ("Bélgica","BE"),
  ("Bahamas","BS"),
  ("Bahrein","BH"),
  ("Bangladesh","BD"),
  ("Barbados","BB"),
  ("Belice","BZ"),
  ("Benín","BJ"),
  ("Bhután","BT"),
  ("Bielorrusia","BY"),
  ("Birmania","MM"),
  ("Bolivia","BO"),
  ("Bosnia y Herzegovina","BA"),
  ("Botsuana","BW"),
  ("Brasil","BR"),
  ("Brunéi","BN"),
  ("Bulgaria","BG"),
  ("Burkina Faso","BF"),
  ("Burundi","BI"),
  ("Cabo Verde","CV"),
  ("Camboya","KH"),
  ("Camerún","CM"),
  ("Canadá","CA"),
  ("Chad","TD"),
  ("Chile","CL"),
  ("China","CN"),
  ("Chipre","CY"),
  ("Ciudad del Vaticano","VA"),
  ("Colombia","CO"),
  ("Comoras","KM"),
  ("República del Congo","CG"),
  ("República Democrática del Congo","CD"),
  ("Corea del Norte","KP"),
  ("Corea del Sur","KR"),
  ("Costa de Marfil","CI"),
  ("Costa Rica","CR"),
  ("Croacia","HR"),
  ("Cuba","CU"),
  ("Curazao","CW"),
  ("Dinamarca","DK"),
  ("Dominica","DM"),
  ("Ecuador","EC"),
  ("Egipto","EG"),
  ("El Salvador","SV"),
  ("Emiratos Árabes Unidos","AE"),
  ("Eritrea","ER"),
  ("Eslovaquia","SK"),
  ("Eslovenia","SI"),
  ("España","ES"),
  ("Estados Unidos de América","US"),
  ("Estonia","EE"),
  ("Etiopía","ET"),
  ("Filipinas","PH"),
  ("Finlandia","FI"),
  ("Fiyi","FJ"),
  ("Francia","FR"),
  ("Gabón","GA"),
  ("Gambia","GM"),
  ("Georgia","GE"),
  ("Ghana","GH"),
  ("Gibraltar","GI"),
  ("Granada","GD"),
  ("Grecia","GR"),
  ("Groenlandia","GL"),
  ("Guadalupe","GP"),
  ("Guam","GU"),
  ("Guatemala","GT"),
  ("Guayana Francesa","GF"),
  ("Guernsey","GG"),
  ("Guinea","GN"),
  ("Guinea Ecuatorial","GQ"),
  ("Guinea-Bissau","GW"),
  ("Guyana","GY"),
  ("Haití","HT"),
  ("Honduras","HN"),
  ("Hong kong","HK"),
  ("Hungría","HU"),
  ("India","IN"),
  ("Indonesia","ID"),
  ("Irán","IR"),
  ("Irak","IQ"),
  ("Irlanda","IE"),
  ("Isla Bouvet","BV"),
  ("Isla de Man","IM"),
  ("Isla de Navidad","CX"),
  ("Isla Norfolk","NF"),
  ("Islandia","IS"),
  ("Islas Bermudas","BM"),
  ("Islas Caimán","KY"),
  ("Islas Cocos (Keeling)","CC"),
  ("Islas Cook","CK"),
  ("Islas de Åland","AX"),
  ("Islas Feroe","FO"),
  ("Islas Georgias del Sur y Sandwich del Sur","GS"),
  ("Islas Heard y McDonald","HM"),
  ("Islas Maldivas","MV"),
  ("Islas Malvinas","FK"),
  ("Islas Marianas del Norte","MP"),
  ("Islas Marshall","MH"),
  ("Islas Pitcairn","PN"),
  ("Islas Salomón","SB"),
  ("Islas Turcas y Caicos","TC"),
  ("Islas Ultramarinas Menores de Estados Unidos","UM"),
  ("Islas Vírgenes Británicas","VG"),
  ("Islas Vírgenes de los Estados Unidos","VI"),
  ("Israel","IL"),
  ("Italia","IT"),
  ("Jamaica","JM"),
  ("Japón","JP"),
  ("Jersey","JE"),
  ("Jordania","JO"),
  ("Kazajistán","KZ"),
  ("Kenia","KE"),
  ("Kirguistán","KG"),
  ("Kiribati","KI"),
  ("Kuwait","KW"),
  ("Líbano","LB"),
  ("Laos","LA"),
  ("Lesoto","LS"),
  ("Letonia","LV"),
  ("Liberia","LR"),
  ("Libia","LY"),
  ("Liechtenstein","LI"),
  ("Lituania","LT"),
  ("Luxemburgo","LU"),
  ("México","MX"),
  ("Mónaco","MC"),
  ("Macao","MO"),
  ("Macedônia","MK"),
  ("Madagascar","MG"),
  ("Malasia","MY"),
  ("Malawi","MW"),
  ("Mali","ML"),
  ("Malta","MT"),
  ("Marruecos","MA"),
  ("Martinica","MQ"),
  ("Mauricio","MU"),
  ("Mauritania","MR"),
  ("Mayotte","YT"),
  ("Micronesia","FM"),
  ("Moldavia","MD"),
  ("Mongolia","MN"),
  ("Montenegro","ME"),
  ("Montserrat","MS"),
  ("Mozambique","MZ"),
  ("Namibia","NA"),
  ("Nauru","NR"),
  ("Nepal","NP"),
  ("Nicaragua","NI"),
  ("Niger","NE"),
  ("Nigeria","NG"),
  ("Niue","NU"),
  ("Noruega","NO"),
  ("Nueva Caledonia","NC"),
  ("Nueva Zelanda","NZ"),
  ("Omán","OM"),
  ("Países Bajos","NL"),
  ("Pakistán","PK"),
  ("Palau","PW"),
  ("Palestina","PS"),
  ("Panamá","PA"),
  ("Papúa Nueva Guinea","PG"),
  ("Paraguay","PY"),
  ("Perú","PE"),
  ("Polinesia Francesa","PF"),
  ("Polonia","PL"),
  ("Portugal","PT"),
  ("Puerto Rico","PR"),
  ("Qatar","QA"),
  ("Reino Unido","GB"),
  ("República Centroafricana","CF"),
  ("República Checa","CZ"),
  ("República Dominicana","DO"),
  ("República de Sudán del Sur","SS"),
  ("Reunión","RE"),
  ("Ruanda","RW"),
  ("Rumanía","RO"),
  ("Rusia","RU"),
  ("Sahara Occidental","EH"),
  ("Samoa","WS"),
  ("Samoa Americana","AS"),
  ("San Bartolomé","BL"),
  ("San Cristóbal y Nieves","KN"),
  ("San Marino","SM"),
  ("San Martín (Francia)","MF"),
  ("San Pedro y Miquelón","PM"),
  ("San Vicente y las Granadinas","VC"),
  ("Santa Elena","SH"),
  ("Santa Lucía","LC"),
  ("Santo Tomé y Príncipe","ST"),
  ("Senegal","SN"),
  ("Serbia","RS"),
  ("Seychelles","SC"),
  ("Sierra Leona","SL"),
  ("Singapur","SG"),
  ("Sint Maarten","SX"),
  ("Siria","SY"),
  ("Somalia","SO"),
  ("Sri lanka","LK"),
  ("Sudáfrica","ZA"),
  ("Sudán","SD"),
  ("Suecia","SE"),
  ("Suiza","CH"),
  ("Surinám","SR"),
  ("Svalbard y Jan Mayen","SJ"),
  ("Swazilandia","SZ"),
  ("Tayikistán","TJ"),
  ("Tailandia","TH"),
  ("Taiwán","TW"),
  ("Tanzania","TZ"),
  ("Territorio Británico del Océano Índico","IO"),
  ("Territorios Australes y Antárticas Franceses","TF"),
  ("Timor Oriental","TL"),
  ("Togo","TG"),
  ("Tokelau","TK"),
  ("Tonga","TO"),
  ("Trinidad y Tobago","TT"),
  ("Tunez","TN"),
  ("Turkmenistán","TM"),
  ("Turquía","TR"),
  ("Tuvalu","TV"),
  ("Ucrania","UA"),
  ("Uganda","UG"),
  ("Uruguay","UY"),
  ("Uzbekistán","UZ"),
  ("Vanuatu","VU"),
  ("Venezuela","VE"),
  ("Vietnam","VN"),
  ("Wallis y Futuna","WF"),
  ("Yemen","YE"),
  ("Yibuti","DJ"),
  ("Zambia","ZM"),
  ("Zimbabue","ZW");

INSERT INTO MARCAS (NOMBRE_DE_MARCA, SISTEMA_OPERATIVO, FECHA_DE_FUNDACION, LUGAR_DE_FUNDACION, FUNDADORES) VALUES
    ('APPLE','IOS','1976-04-01','ESTADOS_UNIDOS_CALIFORNIA','STEVE_JOBS'),
    ('SAMSUNG','ANDROID','1938-03-01','COREA_DEL_SUR_DAEGU','LEE_BYUNG_CHUL'),
    ('HUAWEI','HARMONY_OS','15-09-15','CHINA_SHENZHEN','REN_ZHENGFEI'),
    ('SONY','ANDROID','1946-05-07','JAPON_NIHONBASHI','AKIO_MORITA'),
    ('GOOGLE','ANDROID','1998-09-04','ESTADOS_UNIDOS_CALIFORNIA','LARRY_PAGE'),
    ('OPPO','COLOROS','2004-01-01','CHINA_DONGGUAN','TONY_CHEN'),
    ('ASUS','ANDROID','1989-04-02','TAIWAN_TAIPEI','T.H._TUNG'),
    ('NOTHING','ANDROID','2020-09-29','UNITED_KINGDON_LONDON','CARL_PEI'),
    ('ONEPLUS','OXYGENOS','2013-12-16','SHENZHEN_CHINA','CARL_PEI'),
    ('VIVO','FUNTOUCH_OS_12','2009-01-01','CHINA_DONGGUAN','SHEN_WEI');


INSERT INTO CLIENTES (NOMBRE, APELLIDOS, TELEFONO, EMAIL, DIRECCION, CP, CIUDAD, PAIS) VALUES
    ('SANTIAGO','MONDRAGON','5515964448','SANTY@GMAIL.COM','AVE ALVARO OBREGON 317 A','53100','CDMX',141),
    ('OZCAR','NUNEZ','5586760560','OZCAR@GMAIL.COM','AVE RAMON MENDOZA NO 223','53100','CDMX',141),
    ('EDGAR','PINTO','5562013401','EDGAR@GMAIL.COM','MONTE ALBAN NO. 2574','53100','CDMX',141),
    ('EDSON','GUTIERREZ','5547796350','EDSON@GMAIL.COM','HIDALGO 303','53100','CDMX',141),
    ('CHRISTOPHER','ORTIZ','5526839879','CHRIS@GMAIL.COM','AV. ADOLFO RUIZ CORTINEZ NO. 2103','53100','CDMX',141),
    ('ANDRES','CORTES','5549611984','ANDY@GMAIL.COM','INSURGENTES SUR 265','53100','CDMX',141),
    ('JUAN','LOPEZ','5539131714','JP@GMAIL.COM','AV TEXCOCO MZA 66','53100','CDMX',141),
    ('SEBASTIAN','LEON','5584577497','SEBASTIAN@GMAIL.COM','CONVENTO DE ACTOPAN NO. 62','53100','CDMX',141),
    ('RODRIGO','NERIA','5566806397','POG@GMAIL.COM','LOPEZ MATEOS NO. 171','53100','CDMX',141),
    ('RODRIGO','LEIJA','5547128425','RODRI@GMAIL.COM','CIENFUEGOS 678 NO. 5','53100','CDMX',141);

INSERT INTO MODELOS (NOMBRE_DE_MODELO, LANZAMIENTO_YEAR, ID_MARCAS) VALUES
    ('IPHONE_14_PRO_MAX','2022',1),
    ('S22_ULTRA','2021',2),
    ('P50_PRO','2021',3),
    ('XPERIA_1_IV','2022',4),
    ('GOOGLE_PIXEL_7_PRO','2022',5),
    ('OPPO_FIND_X5_PRO','2022',6),
    ('ASUS_ZENPHONE_9','2022',7),
    ('NOTHING_PHONE(1)','2022',8),
    ('ONEPLUS_10_Pro','2022',9),
    ('VIVO_X80_PRO','2022',10);


INSERT INTO ESPECIFICACIONES (PANTALLA, CAMARA_PRINCIPAL, MEMORIA, PROCESADOR, PRECIO, ID_MODELOS) VALUES 
    ('PANTALLA_SUPER_RETINA_XDR','48MP','6GB','A16_BIONIC','$28.999.00',1),
    ('DYNAMIC_AMOLED_2X','108MP','8GB','EXYNOS_2200','$30.999.00',2),
    ('OLED','50MP','8GB','SNAPDRAGON_888','$24.688.78',3),
    ('OLED_4K_HDR','12MP','12GB','SNAPDRAGON_8_GEN_1','$27.371.87',4),
    ('OLED_LTPO_QHD+','50MP','12GB','GOOGLE_TENZOR_G2','$17.608.78',5),
    ('QHD+','50MP','12GB','SNAPDRAGON_8_GEN_1','$24.853.09',6),
    ('AMOLED','50MP','16GB','SNAPDRAGON_8_GEN_1','$15.290.78',7),
    ('OLED','50MP','12GB','SNAPDRAGON_788G+','$12.888.11',8),
    ('AMOLED_LTPO','48MP','12GB','SNAPDRAGON_8_GEN_1','$16.283.90',9),
    ('AMOLED_WQHD+','50MP','12GB','SNAPDRAGON_8_GEN_1','$15.886.53',10);

INSERT INTO VENTAS (ID_MODELOS, ID_CLIENTES) VALUES 
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
    (6,6),
    (7,7),
    (8,8),
    (9,9),
    (10,10);
