CREATE DATABASE IF NOT EXISTS ProyectoFinal;

USE ProyectoFinal;

CREATE TABLE PAISES
(
    ID_PAISES INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL, 
    DOMINIO CHAR(2) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MARCAS
(
    ID_MARCAS INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DE_MARCA VARCHAR(50) NOT NULL,
    SISTEMA_OPERATIVO VARCHAR(40) NOT NULL,
    FECHA_DE_FUNDACION DATE NOT NULL,
    LUGAR_DE_FUNDACION VARCHAR(80),
    FUNDADORES VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CLIENTES
(
    ID_CLIENTES INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL, 
    TELEFONO VARCHAR(10) UNIQUE NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR(100),
    CP CHAR(5) NOT NULL, 
    CIUDAD VARCHAR(50),
    PAIS INTEGER UNSIGNED,
    FOREIGN KEY (PAIS)
    	REFERENCES PAISES(ID_PAISES)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE MODELOS
(
    ID_MODELOS INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_DE_MODELO VARCHAR(40) NOT NULL, 
    LANZAMIENTO_YEAR YEAR,
    ID_MARCAS INTEGER UNSIGNED,
    FOREIGN KEY (ID_MARCAS)
    	REFERENCES MARCAS(ID_MARCAS)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ESPECIFICACIONES
(
    ID_ESPECIFICACIONES INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PANTALLA VARCHAR(80),
    CAMARA_PRINCIPAL VARCHAR(50),
    MEMORIA VARCHAR(50),
    PROCESADOR VARCHAR(50),
    PRECIO VARCHAR(50),
    ID_MODELOS INTEGER UNSIGNED,
    FOREIGN KEY (ID_MODELOS)
    	REFERENCES MODELOS(ID_MODELOS)
    	ON DELETE RESTRICT
    	ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;

CREATE TABLE VENTAS
(
ID_VENTAS INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ID_MODELOS INTEGER UNSIGNED,
FOREIGN KEY (ID_MODELOS)
	REFERENCES MODELOS(ID_MODELOS)
	ON DELETE RESTRICT 
	ON UPDATE CASCADE,
ID_CLIENTES INTEGER UNSIGNED,
FOREIGN KEY (ID_CLIENTES)
	REFERENCES CLIENTES(ID_CLIENTES)
	ON DELETE RESTRICT
	ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4;